language: java
jdk:
    -openjdk8
addons:
  sonarcloud:
    organization: "simonefesta"
    token:
      secure: "02072c6cba04c202f74435c2d53c7a277d4d8cc6" # encrypted value of your token

script: 
- cd Calcolatrice
- ant build
- sonar-scanner
